[package]
name = "jwt"
version = "0.5.0"
authors = ["Michael Yang <mikkyangg@gmail.com>"]
description = "JSON Web Token library"
documentation = "http://mikkyang.github.io/rust-jwt/doc/jwt/index.html"
homepage = "http://github.com/mikkyang/rust-jwt"
repository = "http://github.com/mikkyang/rust-jwt"
readme = "README.md"
keywords = ["JWT", "token", "web"]
license = "MIT"

[dependencies]
base64 = "0.10"
crypto-mac = "0.7.0"
digest = "0.8.1"
hmac = "0.7.1"
sha2 = "0.8.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
